
[tool.cibuildwheel]
build=["cp313-*", "cp312-*", "cp311-*", "cp310-*"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]


[tool.cibuildwheel.linux]
manylinux-images = ["manylinux2014"]


[tool.cibuildwheel.windows]
archs = ["x86_64", "ARM64"]
