[project]
name = "trm-py"
version = "0.1.0"
description = "Python package including bindings to the trm-cpp library for precision astronomy"
authors = [
    { name = "Pip Grylls", email = "pipgryllsastro@gmail.com"}
]
readme = "README.md"

[build-system]
requires = [
    "scikit-build-core>=0.5.0",
    "scikit-build-core-conan>=0.6.0",
    "setuptools>=75.6.0",
    "pybind11>=2.13.0",
    "conan>=2.9.1"
]
build-backend = "scikit_build_core_conan.build"

[tool.scikit_build_core_conan]
path = "."
build = "missing"
profile = "default"
options = []
settings = []
config = []
generator = "Ninja"
output-folder = "build"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
minimum-version = "build-system.requires"

[tool.scikit-build.cmake]
args = [
    "-DCMAKE_TOOLCHAIN_FILE={source_dir}/build/Release/generators/conan_toolchain.cmake",
    "-DPLPLOT_BUILD_TYPE=4",
    "-DPYTHON_SITE_PACKAGES={python_site_dir}"
]