[tool.poetry]
name = "trm-py"
version = "0.1.0"
description = "Python bindings to the trm-cpp library for precision astronomy"
authors = ["PipGrylls <pipgryllsastro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
astropy = "^6.1.4"

[tool.poetry.dev-dependencies]
python = "^3.11"
conan = "^2.9.1"
setuptools = "^75.6.0"

[tool.poetry.build]
script = "src/build.py"

[build-system]
requires = [
"poetry-core",
"setuptools>=75.6.0",
"pybind11>=2.13.0",
]
build-backend = "poetry.core.masonry.api"

