[project]
name = "trm-py"
version = "0.1.0"
description = "Python package including bindings to the trm-cpp library for precision astronomy"
authors = [
    { name = "Pip Grylls", email = "pipgryllsastro@gmail.com"}
]
readme = "README.md"
packages = [
{ include = "trm_py", from = "." },
{ include = "py_subs", from = "." },
]

[tool.poetry]
include = [
    { path = "py_subs/*.so", format=["sdist", "wheel"]},
    { path = "py_subs/lib/*.dylib", format=["sdist", "wheel"]},
    { path = "py_subs/lib/cmake/**/*.cmake", format=["sdist"]}
]

[tool.poetry.dependencies]
python = ">3.10,<4.0"
astropy = "^6.1.4"
numpy = "^1.21.4"
scipy = "^1.7.3"
pyvista = "^0.45.0"
conan = "^2.15.1"

[poetry.group.dev.dependencies]
python = ">3.10,<4.0"
conan = "^2.9.1"
setuptools = "^75.6.0"

[tool.poetry.build]
script = "py_subs/build.py"

[tool.poetry.scripts]
comdat = "trm_py.doppler.scripts.comdat:comdat"
comdef = "trm_py.doppler.scripts.comdef:comdef"
drlimit = "trm_py.doppler.scripts.drlimit:drlimit"
makedata = "trm_py.doppler.scripts.makedata:makedata"
makegrid = "trm_py.doppler.scripts.makegrid:makegrid"
makemap = "trm_py.doppler.scripts.makemap:makemap"
memit = "trm_py.doppler.scripts.memit:memit"
mol2dopp = "trm_py.doppler.scripts.mol2dopp:mol2dopp"
mspruit = "trm_py.doppler.scripts.mspruit:mspruit"
optgam = "trm_py.doppler.scripts.optgam:optgam"
optscl = "trm_py.doppler.scripts.optscl:optscl"
precover = "trm_py.doppler.scripts.precover:precover"
psearch = "trm_py.doppler.scripts.psearch:psearch"
svdfit = "trm_py.doppler.scripts.svdfit:svdfit"
svd = "trm_py.doppler.scripts.svdfit:svd"
trtest = "trm_py.doppler.scripts.trtest:trtest"
vrend = "trm_py.doppler.scripts.vrend:vrend"

[build-system]
requires = [
"poetry-core",
"setuptools>=75.6.0",
"pybind11>=2.13.0",
"conan>=2.9.1",
"cibuildwheel>=2.14.1",
]
build-backend = "poetry.core.masonry.api"