[project]
name = "trm-py"
version = "0.1.0"
description = "Python package including bindings to the trm-cpp library for precision astronomy"
authors = [
    { name = "Pip Grylls", email = "pipgryllsastro@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = [
    "scikit-build-core>=0.5.0",
    "scikit-build-core-conan>=0.6.0",
    "setuptools>=75.6.0",
    "pybind11>=2.13.0",
    "conan>=2.9.1"
]
build-backend = "scikit_build_core_conan.build"

[tool.scikit_build_core_conan]
path = "."
build = "missing"
options = []
config = []
generator = "Ninja"
output-folder = "build"
[[tool.scikit-build-core-conan.overrides]]
if.platform-system = "Linux"
profile = "ubuntu-latest"
[[tool.scikit-build-core-conan.overrides]]
if.platform-system = "Windows"
profile = "windows-latest"
[[tool.scikit-build-core-conan.overrides]]
if.platform-system = "Darwin"
profile = "macos-latest"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
minimum-version = "build-system.requires"

[tool.scikit-build.cmake]
args = [
    "-DCMAKE_TOOLCHAIN_FILE={source_dir}/build/Release/generators/conan_toolchain.cmake",
    "-DPLPLOT_BUILD_TYPE=2",
    "-DPYTHON_SITE_PACKAGES={python_site_dir}"
]

[tool.scikit-build.sdist]
include = [
    "trm_py/*.so",  # For Unix-like systems
    "trm_py/*.dll", # For Windows
    "trm_py/*.dylib" # For macOS
]