name: Wheels

on:
  push:
    branches:
      - develop
      - remove-lcurve-executables
  pull_request:
    branches:
      - main
      - develop

# The wheels and sdist run when develop is changed via push or pull
# The upload to pypi only happens on main branch which should only happen on a PR
jobs:
    build_wheels:
        name: Wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, macOS-latest]
        steps:

        - uses: actions/checkout@v4
          with:
            submodules: true
      
        - uses: pypa/cibuildwheel@v2.23.3
          env:
            CIBW_BEFORE_BUILD_WINDOWS: |
              vcpkg install plplot
          with:
            config-file: "pyproject.toml"
    
        - uses: actions/upload-artifact@v4
          with:
            name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
            path: ./wheelhouse/*.whl
    
    make_sdist:
        name: Make SDist
        runs-on: ubuntu-latest
        needs: build_wheels
        steps:
          - uses: actions/checkout@v4
            with:
              submodules: true

          - name: Build SDist
            run: pipx run build --sdist
          - name: Upload SDist
            uses: actions/upload-artifact@v4
            with:
              name: cibw-sdist
              path: dist/*.tar.gz
    
    publish-to-pypi:
        name: Publish to PyPI
        # main branch only
        if: github.ref == 'refs/heads/main'
        needs: [build_wheels, make_sdist]
        runs-on: ubuntu-latest
        environment: 
          name: pypi
          url: https://pypi.org/p/trm-py
        permissions:
          id-token: write
        steps:
        - name: Download the wheels
          uses: actions/download-artifact@v4
          with:
            pattern: cibw-*
            path: dist
            merge-multiple: true
        - name: Publish
          uses: pypa/gh-action-pypi-publish@release/v1
        
    publish-to-testpypi:
      name: Publish to TestPyPI
      # develop branch only
      if: github.ref == 'refs/heads/develop'
      needs: [build_wheels, make_sdist]
      runs-on: ubuntu-latest
      environment: 
        name: testpypi
        url: https://test.pypi.org/p/trm-py
      permissions:
        id-token: write
      steps:
      - name: Download the wheels
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
