name: Wheels

on:
  push:
    branches:
      - scikit-build
      - main
  pull_request:
    branches:
      - main

jobs:
    build_wheels:
        name: Wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
    
        - uses: pypa/cibuildwheel@v2.23.3
          with:
            config-file: "pyproject.toml"
    
        - name: Verify clean directory
          run: git diff --exit-code
          shell: bash
    
        - uses: actions/upload-artifact@v4
          with:
            name: cibw-wheels-${{ matrix.os }}
            path: wheelhouse/*.whl
