name: Wheels

on:
  push:
    branches:
      - scikit-build
      - main
      - more-cibuildwheel
  pull_request:
    branches:
      - main

jobs:
    build_wheels:
        name: Wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]
        steps:

        - uses: actions/checkout@v4
          with:
            submodules: true
      
        - uses: pypa/cibuildwheel@v2.23.3
          env:
            CIBW_BEFORE_BUILD_WINDOWS: |
              vcpkg install plplot
          with:
            config-file: "pyproject.toml"
    
        - uses: actions/upload-artifact@v4
          with:
            name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
            path: wheelhouse/*.whl
