name: Wheels

on:
  push:
    branches:
      - scikit-build
      - main
  pull_request:
    branches:
      - main

jobs:
    build_wheels:
        name: Wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
    
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
    
        - uses: astral-sh/setup-uv@v4

        - name: Set CXXFLAGS for OS
          run: |
            if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              echo "CXXFLAGS=-std=c++17" >> $GITHUB_ENV
            elif [[ "${{ matrix.os }}" == "macos-13" || "${{ matrix.os }}" == "macos-latest" ]]; then
              echo "CXXFLAGS=-std=c++17" >> $GITHUB_ENV
            elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
              echo "CXXFLAGS=/std:c++17" >> $GITHUB_ENV
            fi
          shell: bash
    
        - uses: pypa/cibuildwheel@v2.22
          env:
            CIBW_ENABLE: cpython-prerelease
            CIBW_ARCHS_WINDOWS: auto ARM64
            CIBW_ENVIRONMENT: ${{ env.CXXFLAGS }}
    
        - name: Verify clean directory
          run: git diff --exit-code
          shell: bash
    
        - uses: actions/upload-artifact@v4
          with:
            name: cibw-wheels-${{ matrix.os }}
            path: wheelhouse/*.whl
