name: Wheels

on:
  push:
    branches:
      - scikit-build
      - main
  pull_request:
    branches:
      - main

jobs:
    build_wheels:
        name: Wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ linux-intel, linux-arm, windows, macOS-intel, macOS-arm]
            include:
              - archs: auto
                platform: auto
              - os: linux-intel
                runs-on: ubuntu-latest
              - os: linux-arm
                runs-on: ubuntu-24.04-arm
              - os: windows
                runs-on: windows-latest
              - os: macos-intel
                # macos-13 was the last x86_64 runner
                runs-on: macos-13
              - os: macos-arm
                # macos-14+ (including latest) are ARM64 runners
                runs-on: macos-latest
                archs: auto,universal2
            
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: true

        - uses: astral-sh/setup-uv@v4
    
        - uses: pypa/cibuildwheel@v2.23.3
          env:
            CIBW_PLATFORM: ${{ matrix.platform }}
            CIBW_ARCHS: ${{ matrix.archs }}
    
        - name: Verify clean directory
          run: git diff --exit-code
          shell: bash
    
        - uses: actions/upload-artifact@v4
          with:
            name: cibw-wheels-${{ matrix.os }}
            path: wheelhouse/*.whl
